version: '3'

networks:
  main_network: {}

services:
  db:
    container_name: fastapi
    image: postgres:15.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fastapi
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - main_network

  app:
    build: .
    container_name: fastapi-app
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - main_network
