version: '3'

networks:
  main_network: {}

services:
  db:
    container_name: hackaton
    image: postgres:15.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=hackaton
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - main_network

  app:
    build: .
    container_name: hackaton-app
    depends_on:
      - db
    ports:
      - '8000:8000'
    networks:
      - main_network

volumes:
  pgdata:
