version: '3'

services:
  db:
    container_name: fastapi
    image: postgres:15.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fastapi
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    container_name: fastapi-app
    network_mode: host
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: bash -c "uvicorn main:app"